name: "Lint and test"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.0"

        - name: "Run hassfest validation"
          uses: "home-assistant/actions/hassfest@master"

  hacs: # https://github.com/hacs/action
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.0"

        - name: "Run HACS validation"
          uses: "hacs/action@main"
          with:
            category: "integration"
            # Remove this 'ignore' key when you have added brand images for your integration to https://github.com/home-assistant/brands
            ignore: "brands"

  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@v4.2.0"

        - name: "Set up Python"
          uses: actions/setup-python@v5.2.0
          with:
            python-version: "3.12"
            cache: "pip"

        - name: "Install requirements"
          run: python3 -m pip install -r requirements.txt

        - name: "Run"
          run: python3 -m ruff check .
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.2.0"
      - name: Setup Python
        uses: "actions/setup-python@v5.2.0"
        with:
          python-version: "3.12"
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.stiebel_eltron_isg \
            -o console_output_style=count \
            -p no:sugar \
            tests
